plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.minisip'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.minisip'
        minSdk 27
        targetSdk 34
        versionCode 1
        versionName '0.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

// Ни одной внешней зависимости: только платформа Android.
dependencies {
}
